// <auto-generated />
using System;
using InfraStructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InfraStructure.Migrations
{
    [DbContext(typeof(ItecDbContext))]
    [Migration("20260401221341_HorarioDisponibilidade")]
    partial class HorarioDisponibilidade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("BaseModelSequence");

            modelBuilder.Entity("Domain.entities.baseEntities.BaseModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"BaseModelSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Domain.entities.Agendamento", b =>
                {
                    b.HasBaseType("Domain.entities.baseEntities.BaseModel");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("FaturaId")
                        .HasColumnType("bigint");

                    b.Property<long>("ServicoId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TecnicoId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FaturaId");

                    b.HasIndex("ServicoId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("Agendamentos", (string)null);
                });

            modelBuilder.Entity("Domain.entities.Cliente", b =>
                {
                    b.HasBaseType("Domain.entities.baseEntities.BaseModel");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TokenIssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Domain.entities.Fatura", b =>
                {
                    b.HasBaseType("Domain.entities.baseEntities.BaseModel");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("MesReferencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TecnicoId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ValorBruto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorComissao")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasIndex("TecnicoId");

                    b.ToTable("Faturas", (string)null);
                });

            modelBuilder.Entity("Domain.entities.Servico", b =>
                {
                    b.HasBaseType("Domain.entities.baseEntities.BaseModel");

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MaxPreco")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("MinPreco")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TecnicoId")
                        .HasColumnType("bigint");

                    b.HasIndex("TecnicoId");

                    b.ToTable("Servicos", (string)null);
                });

            modelBuilder.Entity("Domain.entities.Tecnico", b =>
                {
                    b.HasBaseType("Domain.entities.baseEntities.BaseModel");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TokenIssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable("Tecnicos", (string)null);
                });

            modelBuilder.Entity("Domain.entities.Agendamento", b =>
                {
                    b.HasOne("Domain.entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.entities.Fatura", "Fatura")
                        .WithMany("Agendamentos")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.entities.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.entities.Tecnico", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Fatura");

                    b.Navigation("Servico");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("Domain.entities.Cliente", b =>
                {
                    b.OwnsOne("Domain.models.Contato", "Contato", b1 =>
                        {
                            b1.Property<long>("ClienteId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Email");

                            b1.Property<string>("Telefone")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Telefone");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.OwnsOne("Domain.models.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<long>("ClienteId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Bairro");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Estado");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Numero");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Pais");

                            b1.Property<string>("Rua")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Rua");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.OwnsOne("Domain.models.FormaPagamento", "FormaPagamento", b1 =>
                        {
                            b1.Property<long>("ClienteId")
                                .HasColumnType("bigint");

                            b1.Property<string>("ChavePix")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ChavePix");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");

                            b1.OwnsOne("Cartao", "Cartao", b2 =>
                                {
                                    b2.Property<long>("FormaPagamentoClienteId")
                                        .HasColumnType("bigint");

                                    b2.Property<int>("AnoExpiracao")
                                        .HasColumnType("integer")
                                        .HasColumnName("AnoExpiracao");

                                    b2.Property<string>("Bandeira")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CartaoBandeira");

                                    b2.Property<string>("CardId")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("CustomerId")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<int>("MesExpiracao")
                                        .HasColumnType("integer")
                                        .HasColumnName("MesExpiracao");

                                    b2.Property<string>("UltimosQuatroDigitos")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CartaoNumero");

                                    b2.HasKey("FormaPagamentoClienteId");

                                    b2.ToTable("Clientes");

                                    b2.WithOwner()
                                        .HasForeignKey("FormaPagamentoClienteId");
                                });

                            b1.Navigation("Cartao")
                                .IsRequired();
                        });

                    b.Navigation("Contato")
                        .IsRequired();

                    b.Navigation("Endereco")
                        .IsRequired();

                    b.Navigation("FormaPagamento")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.entities.Fatura", b =>
                {
                    b.HasOne("Domain.entities.Tecnico", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("Domain.entities.Servico", b =>
                {
                    b.HasOne("Domain.entities.Tecnico", "Tecnico")
                        .WithMany("Servicos")
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("Domain.entities.Tecnico", b =>
                {
                    b.OwnsOne("Domain.models.Contato", "Contato", b1 =>
                        {
                            b1.Property<long>("TecnicoId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Email");

                            b1.Property<string>("Telefone")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Telefone");

                            b1.HasKey("TecnicoId");

                            b1.ToTable("Tecnicos");

                            b1.WithOwner()
                                .HasForeignKey("TecnicoId");
                        });

                    b.OwnsOne("Domain.models.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<long>("TecnicoId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Bairro");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Estado");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Numero");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Pais");

                            b1.Property<string>("Rua")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Rua");

                            b1.HasKey("TecnicoId");

                            b1.ToTable("Tecnicos");

                            b1.WithOwner()
                                .HasForeignKey("TecnicoId");
                        });

                    b.OwnsOne("Domain.models.FormaPagamento", "FormaPagamento", b1 =>
                        {
                            b1.Property<long>("TecnicoId")
                                .HasColumnType("bigint");

                            b1.Property<string>("ChavePix")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ChavePix");

                            b1.HasKey("TecnicoId");

                            b1.ToTable("Tecnicos");

                            b1.WithOwner()
                                .HasForeignKey("TecnicoId");

                            b1.OwnsOne("Cartao", "Cartao", b2 =>
                                {
                                    b2.Property<long>("FormaPagamentoTecnicoId")
                                        .HasColumnType("bigint");

                                    b2.Property<int>("AnoExpiracao")
                                        .HasColumnType("integer")
                                        .HasColumnName("AnoExpiracao");

                                    b2.Property<string>("Bandeira")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CartaoBandeira");

                                    b2.Property<string>("CardId")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("CustomerId")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<int>("MesExpiracao")
                                        .HasColumnType("integer")
                                        .HasColumnName("MesExpiracao");

                                    b2.Property<string>("UltimosQuatroDigitos")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CartaoNumero");

                                    b2.HasKey("FormaPagamentoTecnicoId");

                                    b2.ToTable("Tecnicos");

                                    b2.WithOwner()
                                        .HasForeignKey("FormaPagamentoTecnicoId");
                                });

                            b1.Navigation("Cartao")
                                .IsRequired();
                        });

                    b.OwnsMany("Domain.models.HorarioDisponibilidade", "Horarios", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Dia")
                                .HasColumnType("integer");

                            b1.Property<TimeOnly>("Fim")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly>("Inicio")
                                .HasColumnType("time without time zone");

                            b1.Property<long>("TecnicoId")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.HasIndex("TecnicoId");

                            b1.ToTable("TecnicoHorariosDisponibilidade", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TecnicoId");
                        });

                    b.Navigation("Contato")
                        .IsRequired();

                    b.Navigation("Endereco")
                        .IsRequired();

                    b.Navigation("FormaPagamento")
                        .IsRequired();

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("Domain.entities.Fatura", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("Domain.entities.Tecnico", b =>
                {
                    b.Navigation("Servicos");
                });
#pragma warning restore 612, 618
        }
    }
}
